controller_manager:
  ros__parameters:
    update_rate: 200
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    turntable_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController


turntable_velocity_controller:
  ros__parameters:
    joints: 
      - turntable_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
      - position
      - effort
      
    
    
